{"name": "test_sub[错误]", "status": "failed", "statusDetails": {"message": "AssertionError: assert -200 == 4000", "trace": "self = <test_calNew.Testcal object at 0x000001DB2D7C7320>\nget_cal = <HogwartsLagou05.HomeWorkYing.PytestSecond.calculator.Calculator object at 0x000001DB2D76F400>, get_sub_datas = [100, 300, 4000]\n\n>   ???\nE   assert -200 == 4000\n\nC:\\Users\\zhy\\LGHomeworkUpload\\PytestSecond\\test_calNew.py:21: AssertionError"}, "attachments": [{"name": "stdout", "source": "f52fbfd4-97b4-45b2-b261-f0926267589a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_sub_datas", "value": "[100, 300, 4000]"}], "start": 1627298403206, "stop": 1627298403207, "uuid": "cf931020-db52-4a19-bd58-42b08a1b4ec9", "historyId": "3b6b0ae161aa2b8c31f4ddbbfd8c17df", "testCaseId": "69cdd3803895659524dc220b31d66f08", "fullName": "test_calNew.Testcal#test_sub", "labels": [{"name": "suite", "value": "test_calNew"}, {"name": "subSuite", "value": "Testcal"}, {"name": "host", "value": "DESKTOP-RLF34HD"}, {"name": "thread", "value": "24512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calNew"}]}