{"name": "test_div[错误]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 4000", "trace": "self = <test_calNew.Testcal object at 0x000001DB2D7C7A58>\nget_cal = <HogwartsLagou05.HomeWorkYing.PytestSecond.calculator.Calculator object at 0x000001DB2D76F400>, get_div_datas = [1, 0, 4000]\n\n>   ???\nE   assert None == 4000\n\nC:\\Users\\zhy\\LGHomeworkUpload\\PytestSecond\\test_calNew.py:43: AssertionError"}, "attachments": [{"name": "stdout", "source": "1dc12d0d-f198-4bad-ac0e-5fecbc850218-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "get_div_datas", "value": "[1, 0, 4000]"}], "start": 1627298403279, "stop": 1627298403280, "uuid": "7db7ba1c-8a3b-437d-994a-206b206a0260", "historyId": "a1809c8dcfaeff70945b506302aed516", "testCaseId": "cc8e33b972e0f45f272eb40195c189a4", "fullName": "test_calNew.Testcal#test_div", "labels": [{"name": "suite", "value": "test_calNew"}, {"name": "subSuite", "value": "Testcal"}, {"name": "host", "value": "DESKTOP-RLF34HD"}, {"name": "thread", "value": "24512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calNew"}]}